apiVersion: openclaw.io/v1
kind: Openclaw
metadata:
  name: openclaw-okkk
  namespace: kkk
spec:
  image: 10.29.15.63/ghcr.m.daocloud.io/openclaw/openclaw:20260408
  replicas: 1
  serviceType: NodePort
  gatewayPort: 18789
  gatewayBind: lan
  privacy: true
  customApiKey: "sk-3ZxkdrTPafm91JQ0jkbZdAmd3VzncwbCpJ2E5tD2avLdwZDi"
  customBaseUrl: "https://cdn.12ai.org/v1"
  customModelId: "qwen3.5-plus"
  slmApiKey: "sk-3ZxkdrTPafm91JQ0jkbZdAmd3VzncwbCpJ2E5tD2avLdwZDi"
  slmApiUrl: "https://cdn.12ai.org/v1"
  slmModelId: "gpt4-mini"
  customProviderId: "ppnb"
  customCompatibility: openai
  storage:
    accessModes:
      - ReadWriteOnce
    storage: 20Gi
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
