apiVersion: openclaw.io/v1
kind: Openclaw
metadata:
  name: openclaw-okkk-test
  namespace: clawtest
spec:
  image: 10.29.15.63/ghcr.m.daocloud.io/openclaw/openclaw:20260410
  replicas: 1
  serviceType: NodePort
  gatewayPort: 18789
  gatewayBind: lan
  privacy: true
  customApiKey: "<your api key>"
  customBaseUrl: "<your ai baseurl>"
  customModelId: "qwen3.5-plus"
  slmApiKey: "<your api key>"
  slmApiUrl: "<your ai baseurl>"
  slmModelId: "deepseek-v3.2"
  customProviderId: "ppnb"
  customCompatibility: openai
  redis:
    address: "10.29.15.65:32667"
    password: "ZD32N0Yce9l6"
    db: 10
  storage:
    accessModes:
      - ReadWriteOnce
    storage: 20Gi
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
